// Code generated by abi-gen v1. DO NOT EDIT.

use core::ffi::c_void;

pub const DF_ABI_VERSION: u32 = 1;
pub const DF_STATUS_OK: DfStatus = 0;
pub const DF_STATUS_ERROR: DfStatus = 1;
pub type DfStatus = i32;
pub type DfEventId = u32;

#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerId { pub bytes: [u8; 16], pub generation: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfVec3 { pub x: f64, pub y: f64, pub z: f64 }
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfRotation { pub yaw: f32, pub pitch: f32 }
#[repr(C)]
#[derive(Clone, Copy, Debug)]
pub struct DfStringView { pub data: *const u8, pub len: u64 }
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfAbiHeader { pub abi_version: u32, pub struct_size: u32, pub subscriptions: u64 }

pub const DF_EVENT_PLAYER_MOVE: DfEventId = 1;
pub const DF_SUBSCRIPTION_PLAYER_MOVE: u64 = 1u64 << 0;
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerMoveInput {
    pub player: DfPlayerId,
    pub old_position: DfVec3,
    pub new_position: DfVec3,
    pub rotation: DfRotation,
}
#[repr(C)]
#[derive(Clone, Copy, Debug, Default)]
pub struct DfPlayerMoveState {
    pub cancelled: u8,
}

pub type DfPluginCreateFn = unsafe extern "C" fn() -> *mut c_void;
pub type DfPluginDestroyFn = unsafe extern "C" fn(instance: *mut c_void);
pub type DfHandleEventFn = unsafe extern "C" fn(instance: *mut c_void, event_id: DfEventId, input: *const c_void, state: *mut c_void) -> DfStatus;

#[repr(C)]
pub struct DfPluginApiV1 {
    pub header: DfAbiHeader,
    pub plugin_id: DfStringView,
    pub create: Option<DfPluginCreateFn>,
    pub destroy: Option<DfPluginDestroyFn>,
    pub handle_event: Option<DfHandleEventFn>,
}

pub type DfPluginEntryV1Fn = unsafe extern "C" fn() -> *const DfPluginApiV1;

unsafe impl Sync for DfPluginApiV1 {}
