// Code generated by abi-gen v1. DO NOT EDIT.

package native

/*
#include "bridge.h"
*/
import "C"

import "math"

type generatedPlayerOperationsHost interface {
	SetPlayerExperience(InvocationID, PlayerID, int32, float64) bool
}

func (noopHost) SetPlayerExperience(InvocationID, PlayerID, int32, float64) bool { return false }

//export bg_go_player_experience_set
func bg_go_player_experience_set(context C.uint64_t, invocation C.DfInvocationId, player C.DfPlayerId, level C.int32_t, progress C.double) C.DfStatus {
	levelValue := int32(level)
	progressValue := float64(progress)
	host, ok := resolveHost(uint64(context))
	if !ok || levelValue < 0 || math.IsNaN(progressValue) || math.IsInf(progressValue, 0) || progressValue < 0 || progressValue > 1 || !host.SetPlayerExperience(InvocationID(invocation), playerID(player), levelValue, progressValue) {
		return C.DF_STATUS_ERROR
	}
	return C.DF_STATUS_OK
}
