// Code generated by abi-gen v1. DO NOT EDIT.

package native

type PlayerStateKind uint32

const (
	PlayerStateGameMode           PlayerStateKind = 0
	PlayerStateHeal               PlayerStateKind = 1
	PlayerStateHurt               PlayerStateKind = 2
	PlayerStateFood               PlayerStateKind = 3
	PlayerStateMaxHealth          PlayerStateKind = 4
	PlayerStateHealth             PlayerStateKind = 5
	PlayerStateExperienceLevel    PlayerStateKind = 6
	PlayerStateExperienceProgress PlayerStateKind = 7
)

type PlayerStateValue struct {
	Number  float64
	Integer int64
}
