// Code generated by abi-gen v1. DO NOT EDIT.

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Speed;
impl private::Sealed for Speed {}
impl Type for Speed { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_SPEED } }
impl LastingType for Speed {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Slowness;
impl private::Sealed for Slowness {}
impl Type for Slowness { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_SLOWNESS } }
impl LastingType for Slowness {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Haste;
impl private::Sealed for Haste {}
impl Type for Haste { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_HASTE } }
impl LastingType for Haste {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct MiningFatigue;
impl private::Sealed for MiningFatigue {}
impl Type for MiningFatigue { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_MINING_FATIGUE } }
impl LastingType for MiningFatigue {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Strength;
impl private::Sealed for Strength {}
impl Type for Strength { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_STRENGTH } }
impl LastingType for Strength {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct InstantHealth;
impl private::Sealed for InstantHealth {}
impl Type for InstantHealth { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_INSTANT_HEALTH } }
impl InstantType for InstantHealth {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct InstantDamage;
impl private::Sealed for InstantDamage {}
impl Type for InstantDamage { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_INSTANT_DAMAGE } }
impl InstantType for InstantDamage {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct JumpBoost;
impl private::Sealed for JumpBoost {}
impl Type for JumpBoost { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_JUMP_BOOST } }
impl LastingType for JumpBoost {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Nausea;
impl private::Sealed for Nausea {}
impl Type for Nausea { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_NAUSEA } }
impl LastingType for Nausea {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Regeneration;
impl private::Sealed for Regeneration {}
impl Type for Regeneration { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_REGENERATION } }
impl LastingType for Regeneration {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Resistance;
impl private::Sealed for Resistance {}
impl Type for Resistance { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_RESISTANCE } }
impl LastingType for Resistance {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct FireResistance;
impl private::Sealed for FireResistance {}
impl Type for FireResistance { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_FIRE_RESISTANCE } }
impl LastingType for FireResistance {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct WaterBreathing;
impl private::Sealed for WaterBreathing {}
impl Type for WaterBreathing { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_WATER_BREATHING } }
impl LastingType for WaterBreathing {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Invisibility;
impl private::Sealed for Invisibility {}
impl Type for Invisibility { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_INVISIBILITY } }
impl LastingType for Invisibility {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Blindness;
impl private::Sealed for Blindness {}
impl Type for Blindness { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_BLINDNESS } }
impl LastingType for Blindness {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct NightVision;
impl private::Sealed for NightVision {}
impl Type for NightVision { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_NIGHT_VISION } }
impl LastingType for NightVision {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Hunger;
impl private::Sealed for Hunger {}
impl Type for Hunger { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_HUNGER } }
impl LastingType for Hunger {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Weakness;
impl private::Sealed for Weakness {}
impl Type for Weakness { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_WEAKNESS } }
impl LastingType for Weakness {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Poison;
impl private::Sealed for Poison {}
impl Type for Poison { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_POISON } }
impl LastingType for Poison {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Wither;
impl private::Sealed for Wither {}
impl Type for Wither { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_WITHER } }
impl LastingType for Wither {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct HealthBoost;
impl private::Sealed for HealthBoost {}
impl Type for HealthBoost { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_HEALTH_BOOST } }
impl LastingType for HealthBoost {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Absorption;
impl private::Sealed for Absorption {}
impl Type for Absorption { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_ABSORPTION } }
impl LastingType for Absorption {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Saturation;
impl private::Sealed for Saturation {}
impl Type for Saturation { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_SATURATION } }
impl LastingType for Saturation {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Levitation;
impl private::Sealed for Levitation {}
impl Type for Levitation { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_LEVITATION } }
impl LastingType for Levitation {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct FatalPoison;
impl private::Sealed for FatalPoison {}
impl Type for FatalPoison { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_FATAL_POISON } }
impl LastingType for FatalPoison {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct ConduitPower;
impl private::Sealed for ConduitPower {}
impl Type for ConduitPower { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_CONDUIT_POWER } }
impl LastingType for ConduitPower {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct SlowFalling;
impl private::Sealed for SlowFalling {}
impl Type for SlowFalling { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_SLOW_FALLING } }
impl LastingType for SlowFalling {}

#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Darkness;
impl private::Sealed for Darkness {}
impl Type for Darkness { fn id(self) -> i32 { dragonfly_plugin_sys::DF_EFFECT_DARKNESS } }
impl LastingType for Darkness {}
