// Code generated by abi-gen v1. DO NOT EDIT.

impl Player {
    pub fn message(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_MESSAGE, value); }
    pub fn send_tip(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_TIP, value); }
    pub fn send_popup(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_POPUP, value); }
    pub fn send_jukebox_popup(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_JUKEBOX_POPUP, value); }
    pub fn set_name_tag(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_NAME_TAG, value); }
    pub fn disconnect(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_DISCONNECT, value); }
    pub fn kick(&self, value: &str) { self.send_text(dragonfly_plugin_sys::DF_PLAYER_TEXT_KICK, value); }
    pub fn set_game_mode(&self, value: GameMode) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_GAME_MODE, 0.0, value as i64); }
    pub fn game_mode(&self) -> GameMode { match self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_GAME_MODE).integer { 1 => GameMode::Creative, 2 => GameMode::Adventure, 3 => GameMode::Spectator, _ => GameMode::Survival } }
    pub fn set_food(&self, value: i32) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_FOOD, 0.0, i64::from(value)); }
    pub fn food(&self) -> i32 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_FOOD).integer as i32 }
    pub fn set_max_health(&self, value: f64) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_MAX_HEALTH, value, 0); }
    pub fn max_health(&self) -> f64 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_MAX_HEALTH).number }
    pub fn health(&self) -> f64 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_HEALTH).number }
    pub fn set_experience_level(&self, value: i32) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_EXPERIENCE_LEVEL, 0.0, i64::from(value)); }
    pub fn experience_level(&self) -> i32 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_EXPERIENCE_LEVEL).integer as i32 }
    pub fn set_experience_progress(&self, value: f64) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_EXPERIENCE_PROGRESS, value, 0); }
    pub fn experience_progress(&self) -> f64 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_EXPERIENCE_PROGRESS).number }
    pub fn set_scale(&self, value: f64) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_SCALE, value, 0); }
    pub fn scale(&self) -> f64 { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_SCALE).number }
    pub fn set_invisible(&self, value: bool) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_INVISIBLE, 0.0, value as i64); }
    pub fn invisible(&self) -> bool { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_INVISIBLE).integer != 0 }
    pub fn set_immobile(&self, value: bool) { self.set_state(dragonfly_plugin_sys::DF_PLAYER_STATE_IMMOBILE, 0.0, value as i64); }
    pub fn immobile(&self) -> bool { self.state(dragonfly_plugin_sys::DF_PLAYER_STATE_IMMOBILE).integer != 0 }
    /// Performs the `experience` player operation. Invalid values and unavailable hosts are ignored.
    pub fn set_experience(&self, level: i32, progress: f64) {
        if level < 0 || !progress.is_finite() || !(0.0..=1.0).contains(&progress) { return; }
        let Some(host) = host_api() else { return };
        let Some(call) = host.player_experience_set else { return };
        let _ = unsafe { call(host.context, current_invocation(), self.raw_id(), level, progress) };
    }
}
