using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Dragonfly.Generator;

[Generator]
public sealed class PluginEntryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var plugins = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (syntax, _) => PluginType(syntax))
            .Where(static plugin => plugin.HasValue)
            .Select(static (plugin, _) => plugin!.Value);

        context.RegisterSourceOutput(plugins.Collect(), static (output, types) =>
        {
            if (types.Length == 0) return;
            var plugin = types[0];
            output.AddSource("DragonflyPluginEntry.g.cs", $$"""
                // <auto-generated />
                namespace Dragonfly.Generated;

                internal static unsafe class PluginEntry
                {
                    [global::System.Runtime.InteropServices.UnmanagedCallersOnly(
                        EntryPoint = "df_plugin_entry_v4",
                        CallConvs = [typeof(global::System.Runtime.CompilerServices.CallConvCdecl)])]
                    public static global::Dragonfly.Native.PluginApi* Load() =>
                        global::Dragonfly.PluginExport<{{plugin.Type}}>.Api({{plugin.Subscriptions}}UL);
                }
                """);
        });
    }

    private static PluginInfo? PluginType(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol type || type.IsAbstract)
            return null;
        for (var current = type.BaseType; current is not null; current = current.BaseType)
            if (current.ToDisplayString() == "Dragonfly.Plugin")
            {
                ulong subscriptions = 0;
                foreach (var method in type.GetMembers().OfType<IMethodSymbol>())
                {
                    if (!method.IsOverride) continue;
                    foreach (var attribute in method.OverriddenMethod?.GetAttributes() ?? [])
                    {
                        if (attribute.AttributeClass?.ToDisplayString() != "Dragonfly.HandlerSubscriptionAttribute" ||
                            attribute.ConstructorArguments.Length != 1 ||
                            attribute.ConstructorArguments[0].Value is not ulong value) continue;
                        subscriptions |= value;
                    }
                }
                return new PluginInfo(
                    type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    subscriptions);
            }
        return null;
    }

    private readonly struct PluginInfo(string type, ulong subscriptions)
    {
        public string Type { get; } = type;
        public ulong Subscriptions { get; } = subscriptions;
    }
}
