using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Dragonfly.Generator;

[Generator]
public sealed class PluginEntryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var plugins = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                static (syntax, _) => PluginType(syntax))
            .Where(static type => type is not null);

        context.RegisterSourceOutput(plugins.Collect(), static (output, types) =>
        {
            var plugin = types.FirstOrDefault();
            if (plugin is null) return;
            output.AddSource("DragonflyPluginEntry.g.cs", $$"""
                // <auto-generated />
                namespace Dragonfly.Generated;

                internal static unsafe class PluginEntry
                {
                    [global::System.Runtime.InteropServices.UnmanagedCallersOnly(
                        EntryPoint = "df_plugin_entry_v4",
                        CallConvs = [typeof(global::System.Runtime.CompilerServices.CallConvCdecl)])]
                    public static global::Dragonfly.Native.PluginApi* Load() =>
                        global::Dragonfly.PluginExport<{{plugin}}>.Api;
                }
                """);
        });
    }

    private static string? PluginType(GeneratorSyntaxContext context)
    {
        var declaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(declaration) is not INamedTypeSymbol type || type.IsAbstract)
            return null;
        for (var current = type.BaseType; current is not null; current = current.BaseType)
            if (current.ToDisplayString() == "Dragonfly.Plugin")
                return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return null;
    }
}
