// Code generated by abi-gen v1. DO NOT EDIT.

package host

import (
	"math"

	"github.com/bedrock-gophers/plugins/internal/native"
	"github.com/df-mc/dragonfly/server/player"
	"github.com/df-mc/dragonfly/server/world"
)

func setPlayerState(connected *player.Player, kind native.PlayerStateKind, value native.PlayerStateValue) bool {
	switch kind {
	case native.PlayerStateGameMode:
		mode, ok := world.GameModeByID(int(value.Integer))
		if !ok {
			return false
		}
		connected.SetGameMode(mode)
	case native.PlayerStateHeal:
		if math.IsNaN(value.Number) || math.IsInf(value.Number, 0) || value.Number < 0 {
			return false
		}
		connected.Heal(value.Number, pluginHealingSource{})
	case native.PlayerStateHurt:
		if math.IsNaN(value.Number) || math.IsInf(value.Number, 0) || value.Number < 0 {
			return false
		}
		connected.Hurt(value.Number, pluginDamageSource{})
	case native.PlayerStateFood:
		if value.Integer < math.MinInt32 || value.Integer > math.MaxInt32 {
			return false
		}
		connected.SetFood(int(value.Integer))
	case native.PlayerStateMaxHealth:
		if math.IsNaN(value.Number) || math.IsInf(value.Number, 0) || value.Number <= 0 {
			return false
		}
		connected.SetMaxHealth(value.Number)
	case native.PlayerStateExperienceLevel:
		if value.Integer < math.MinInt32 || value.Integer > math.MaxInt32 || value.Integer < 0 {
			return false
		}
		connected.SetExperienceLevel(int(value.Integer))
	case native.PlayerStateExperienceProgress:
		if math.IsNaN(value.Number) || math.IsInf(value.Number, 0) || value.Number < 0 || value.Number > 1 {
			return false
		}
		connected.SetExperienceProgress(value.Number)
	default:
		return false
	}
	return true
}

func readPlayerState(connected *player.Player, kind native.PlayerStateKind) (native.PlayerStateValue, bool) {
	switch kind {
	case native.PlayerStateGameMode:
		value, ok := world.GameModeID(connected.GameMode())
		return native.PlayerStateValue{Integer: int64(value)}, ok
	case native.PlayerStateFood:
		return native.PlayerStateValue{Integer: int64(connected.Food())}, true
	case native.PlayerStateMaxHealth:
		return native.PlayerStateValue{Number: connected.MaxHealth()}, true
	case native.PlayerStateHealth:
		return native.PlayerStateValue{Number: connected.Health()}, true
	case native.PlayerStateExperienceLevel:
		return native.PlayerStateValue{Integer: int64(connected.ExperienceLevel())}, true
	case native.PlayerStateExperienceProgress:
		return native.PlayerStateValue{Number: connected.ExperienceProgress()}, true
	default:
		return native.PlayerStateValue{}, false
	}
}
